# Generated by Django 5.1 on 2026-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_full_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
