# Generated by Django 5.1 on 2024-09-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_No',
            new_name='contact_no',
        ),
    ]
