# Generated by Django 5.1 on 2026-01-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendancestatus'),
        ),
    ]
