# Generated by Django 5.1 on 2026-02-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='hra',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
