# Generated by Django 5.1 on 2026-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
